#' @rdname run_metrics
#' @title run_metrics
#'
#' Insert description of run_metrics here
#'
#' @param daf a \code{\link[SingleCellExperiment]{SingleCellExperiment}}, this was generated after running examples present
#'   in the vignette.
#' @param raw_dir String: Directory to file containing raw data.
#' @param method_names Vector: Strings that describe method names.
#'   e.g. c(cytonorm, batchadj, cytofruv)
#' @param data_dir List: Strings of directories that contain appropriate data.
#'   IMPORTANT: Order of directory strings should correlate with order of method names in method_names.
#'   Note the directory for cytofRUV processed data is a vector of strings.
#'   e.g. c("../Cytofnorm_Cytof_Package/EMD_metric_comp_norm_all_samples_all_cells.rds",
#'          "../BatchAdjust/BatchAdjust_95p_and_DG23_new_trial/EMD_metric_comp_norm_all_samples_all_cells.rds"
#'          c("CytofRUV_Norm_data_CLL2_HC1_all_cl_20_k5/EMD_metric_comp_norm_all_samples_all_cells.rds",
#'            "CytofRUV_Norm_data_CLL2_HC1_all_cl_20_k15/EMD_metric_comp_norm_all_samples_all_cells.rds",
#'            "CytofRUV_Norm_data_CLL2_HC1_all_cl_20_k20/EMD_metric_comp_norm_all_samples_all_cells.rds"
#'          )
#'          )
#' @param k Vector: cluster numbers to be inspected, default val: c(5,10,15)
#' @param filter_patients Vector: relevant patient IDs  e.g. val = c("LL1_B1","LL2_B1","LL3_B1") that is,
#'   display patient IDs that contain: "LL1_B1","LL2_B1","LL3_B1".
#' @param x_axis_name String: Will be shared by all x-axis labels will share in common. E.g. "CLL", results in
#'   x-axis items = "CLL1, CLL2, CLL3"
#' @param cols Vector: Strings of colours for plot annotations. Default val:
#'   c("raw"="black","batchadj"="indianred4","cytonorm"="darkmagenta","cytofruv_k1"="#084081","cytofruv_k3"="#0868AC","cytofruv_k5"="#2B8CBE","cytofruv_k7"="#4EB3D3","cytofruv_k10"="#7BCCC4","cytofruv_k12"= "#A8DDB5","cytofruv_k15"="darkgreen","cytofruv_k20"="seagreen","cytofruv_k25"="yellowgreen")
#'
#'
#' @param raw_files String: Directory that contains raw data files.
#' @param cluster_to_select_raw_data Vector: Integers representing cluster_ID to inspect for raw data.
#' @param norm_files String: Directory that contains normalised data files.
#' @param outdir String: Directory to store output files generated by run_metrics.
#' @param cluster_to_select_norm_data Vector: Integers representing cluster_ID to inspect for normalized data.
#' @param rep_samples Vector: Strings of samples IDs to inspect.
#' @param nb_cells=10000 Int: Number of cells to run metrics across.
#' @param props_table_raw String: Directory to file which contains proportions table for raw data.
#' @param props_table_norm String: Directory to file which contains proportions table for normalised data.
#'
#' @export
run_metrics <- function(raw_files,cluster_to_select_raw_data,norm_files,outdir,cluster_to_select_norm_data,rep_samples,nb_cells=10000,props_table_raw,props_table_norm){
  ### METRICS TO ANALYSE PERFORMANCE OF THE NORMALISATION
  # library(cluster)
  # library(MASS)
  # library(ruv)
  # library(rsvd)
  # library("gridExtra")
  # library("ggpubr")
  # library("tidyverse")
  # library("RColorBrewer")
  # library(purrr)
  # library(matrixStats)
  # library(ggplot2)
  # library(reshape2)
  # library(RColorBrewer)
  # library(pheatmap)

  files <- c(raw_files, norm_files)
  file=c(1,2)
  data_list <- map(files, ~readRDS(.))
  raw_data=data_list[[1]]
  norm_data=data_list[[2]]
  colnames(norm_data) <- gsub("^X", "",  colnames(norm_data))
  colnames(raw_data) <- gsub("^X", "",  colnames(raw_data))
  nb_markers=dim(raw_data)[2]-2
  nclust=dim(props_table_norm)[1]
  nsample=dim(props_table_norm)[2]
  all_samples=colnames(props_table_norm)
  all_cluster=rownames(props_table_norm)

  ############################ 1.Silhouette and LDA on the Silhouette
  silhouette_specific_clusters <- function (cluster_to_select,rep_samples,nb_cells,data)
  {
    sample_ids=data$sample
    cell_clustering1=data$cluster
    expr= as.matrix(data[, 3:ncol(data)])
    colnames(expr) <- gsub("^X", "",  colnames(expr))
    rep_sample_ids=sample_ids[sample_ids%in%rep_samples]
    rep_expr=expr[sample_ids%in%rep_samples,]
    rep_cell_clustering=cell_clustering1[sample_ids%in%rep_samples]
    rep_sample_ids=rep_sample_ids[rep_cell_clustering%in%cluster_to_select]
    rep_expr=rep_expr[rep_cell_clustering%in%cluster_to_select,]
    rep_cell_clustering=rep_cell_clustering[rep_cell_clustering%in%cluster_to_select]
    ## Overall effect of bio vs batch with subsampling
    rep_data=data.frame(rep_expr,clust=as.numeric(rep_cell_clustering),batch=as.numeric(substr(rep_sample_ids,nchar(as.character(rep_sample_ids)), nchar(as.character(rep_sample_ids)))))
    colnames(rep_data) <- gsub("^X", "",  colnames(rep_data))
    base::set.seed(1234)
    subs_rep_data=rep_data[sample(nrow(rep_data), nb_cells), ]
    ## Silhouette
    over_ss_biology=silhouette(subs_rep_data$clust,dist(subs_rep_data[,1:ncol(data)]))
    over_ss_batch=silhouette(subs_rep_data$batch,dist(subs_rep_data[,1:ncol(data)]))
    over_ss<- c(bio = mean(over_ss_biology[,"sil_width"]), batch = mean(over_ss_batch[,"sil_width"]))
    #saveRDS(over_ss, paste(outdir,"Sil_Rep_",paste(c(rep_samples),collapse="_"),"_Clust_",paste(c(cluster_to_select),collapse="_"),"_",datatype,"_data_over_ss.rds",sep=""))
    return (over_ss)
  }

  silhouette_and_LDA_specific_clusters <- function (cluster_to_select,rep_samples,nb_cells,data,datatype){
    sample_ids=data$sample
    cell_clustering1=data$cluster
    expr= as.matrix(data[, 3:ncol(data)])
    colnames(expr) <- gsub("^X", "",  colnames(expr))
    rep_sample_ids=sample_ids[sample_ids%in%rep_samples]
    rep_expr=expr[sample_ids%in%rep_samples,]
    rep_cell_clustering=cell_clustering1[sample_ids%in%rep_samples]
    rep_sample_ids=rep_sample_ids[rep_cell_clustering%in%cluster_to_select]
    rep_expr=rep_expr[rep_cell_clustering%in%cluster_to_select,]
    rep_cell_clustering=rep_cell_clustering[rep_cell_clustering%in%cluster_to_select]
    ## Overall effect of bio vs batch with subsampling
    rep_data=data.frame(rep_expr,clust=as.numeric(rep_cell_clustering),batch=as.numeric(substr(rep_sample_ids,nchar(as.character(rep_sample_ids)), nchar(as.character(rep_sample_ids)))))
    colnames(rep_data) <- gsub("^X", "",  colnames(rep_data))
    base::set.seed(1234)
    subs_rep_data=rep_data[sample(nrow(rep_data), nb_cells), ]
    ## Silhouette
    over_ss_biology=silhouette(subs_rep_data$clust,dist(subs_rep_data[,1:ncol(data)]))
    over_ss_batch=silhouette(subs_rep_data$batch,dist(subs_rep_data[,1:ncol(data)]))
    over_ss<- c(bio = mean(over_ss_biology[,"sil_width"]), batch = mean(over_ss_batch[,"sil_width"]))
    saveRDS(over_ss, paste(outdir,"Sil_Rep_",paste(c(rep_samples),collapse="_"),"_Clust_",paste(c(cluster_to_select),collapse="_"),"_",datatype,"_data_over_ss.rds",sep=""))
    ### LDS plot
    batches=c(1,2)
    batch_data=subs_rep_data[subs_rep_data$batch%in%batches,]
    subs.lda2batch <- lda(clust + batch ~., data =batch_data )
    subs.lda.values <- predict(subs.lda2batch, batch_data[,1:ncol(data)])
    #convert to data frame
    color_batch=c("#0072B2","#D55E00")
    newbatch_data <- data.frame(batch = factor(batch_data$batch),cluster = factor(batch_data$clust), LDA1 = subs.lda.values$x[,1],LDA2 = subs.lda.values$x[,2],samp=paste("Rep_",batch_data$batch,"_Clust_",batch_data$clust,sep=""))
    ggplot(newbatch_data) + geom_point(aes(LDA1,LDA2,colour = batch,shape=cluster), size = 2.5) +
      scale_color_manual(values = color_batch) +
      guides(col = guide_legend(overide.aes = list(alpha = 1, size = 5))) +
      theme_bw() +
      theme(aspect.ratio = 1,
            panel.grid.minor = element_blank(),
            panel.grid.major = element_line(color = "lightgrey",size = 0.5))+
      theme(text = element_text(size=20), legend.title = element_text(size = 20),
            legend.text = element_text(size = 20),
            axis.text.x = element_text(angle=90, hjust=1))
    ggsave(paste(outdir,"LDA_Rep_",paste(c(rep_samples),collapse="_"),"_Clust_",paste(c(cluster_to_select),collapse="_"),"_",datatype,"_data.png",sep=""))
  }

  # ## All samples
  ind=1
  sil_raw_all_samples=matrix(nrow=nsample/2,ncol=3)
  colnames(sil_raw_all_samples)=c("samples","bio","batch")
  sil_raw_all_samples[,1]=substring(colnames(props_table_norm)[seq(1,nsample,2)],first=1,last = 4)
  sil_norm_all_samples=sil_raw_all_samples
  for (s in seq(1,nsample,2)){
    rep_samples_sel=colnames(props_table_norm)[c(s,s+1)]
    sraw=silhouette_specific_clusters(all_cluster,rep_samples_sel,nb_cells,data=data_list[[1]])
    sil_raw_all_samples[ind,2:3]=sraw
    snorm=silhouette_specific_clusters(all_cluster,rep_samples_sel,nb_cells,data=data_list[[2]])
    sil_norm_all_samples[ind,2:3]=snorm
    ind=ind+1
  }
  saveRDS(sil_raw_all_samples, paste(outdir,"Sil_all_samples_all_clust_raw_data_over_ss.rds",sep=""))
  saveRDS(sil_norm_all_samples, paste(outdir,"Sil_all_samples_all_clust_norm_data_over_ss.rds",sep=""))

  ############################ 2. EMD
  EMD_metric <- function (data,binSize=0.005){
    nb_markers=dim(data[[1]])[2]
    distr <- list()
    for(file in c(1:length(files))){
      distr[[file]] <-  apply(data[[file]][,3:nb_markers],2,function(x){
        graphics::hist(x,
                       breaks = seq(-500,500,by=binSize),
                       plot = FALSE)$counts
      })
    }

    distances <- matrix(nrow=1,ncol=(nb_markers-3+1))
    colnames(distances)=colnames(data[[1]])[3:nb_markers]
    for(marker in c(1:(nb_markers-3+1))){
      distances[marker] <-
        emdist::emd2d(
          matrix(distr[[1]][,marker]),
          matrix(distr[[2]][,marker]))
    }
    return(distances)
  }

  ## EMD metric for rep samples per cluster
  EMD_per_cluster <- function(rep1,rep2){
    rep_comp_clust=matrix(nrow=nclust,ncol=nb_markers)
    colnames(rep_comp_clust)= colnames(data_list[[1]])[3:ncol(data_list[[1]])]
    row.names(rep_comp_clust)=paste("Cl_",seq(1,nclust),sep="")
    for (c in c(1:nclust)){
      rep1_clust_c=rep1[rep1$clust%in%c,]
      rep2_clust_c=rep2[rep2$clust%in%c,]
      rep_clust_c=list(rep1_clust_c,rep2_clust_c)
      rep_comp_clust[c,]=EMD_metric(rep_clust_c)
    }
    return(rep_comp_clust)
  }

  ## EMD metric for rep samples per cluster
  cluster_to_use=norm_data$cluster # !!!! IMPORTANT
  raw_data_tmp=raw_data
  raw_data_tmp$cluster=cluster_to_use
  raw_rep1=raw_data_tmp[raw_data$sample%in%rep_samples[1],]
  raw_rep2=raw_data_tmp[raw_data$sample%in%rep_samples[2],]
  norm_rep1=norm_data[norm_data$sample%in%rep_samples[1],]
  norm_rep2=norm_data[norm_data$sample%in%rep_samples[2],]
  raw_rep_comp_clust=EMD_per_cluster(raw_rep1,raw_rep2)
  norm_rep_comp_clust=EMD_per_cluster(norm_rep1,norm_rep2)
  saveRDS(raw_rep_comp_clust, paste(outdir,"EMD_metric_raw_data_per_cluster_",paste(c(rep_samples),collapse="_"),".rds",sep=""))
  saveRDS(norm_rep_comp_clust, paste(outdir,"EMD_metric_norm_data_per_cluster_",paste(c(rep_samples),collapse="_"),".rds",sep=""))
  ## EMD metric for all rep samples all cells
  ind=1
  EMD_metric_comp_raw_all_samples=matrix(nrow=nsample/2,ncol=nb_markers)
  colnames(EMD_metric_comp_raw_all_samples)=colnames(data_list[[1]])[3:ncol(data_list[[1]])]
  row.names(EMD_metric_comp_raw_all_samples)=substring(colnames(props_table_norm)[seq(1,nsample,2)],2)
  EMD_metric_comp_norm_all_samples=EMD_metric_comp_raw_all_samples
  for (s in seq(1,nsample,2)){
    rep_samples_sel=colnames(props_table_norm)[c(s,s+1)]
    raw_rep1=data_list[[1]][data_list[[1]]$sample%in%rep_samples_sel[1],]
    raw_rep2=data_list[[1]][data_list[[1]]$sample%in%rep_samples_sel[2],]
    norm_rep1=data_list[[2]][data_list[[1]]$sample%in%rep_samples_sel[1],]
    norm_rep2=data_list[[2]][data_list[[1]]$sample%in%rep_samples_sel[2],]
    raw_rep=list(raw_rep1,raw_rep2)
    norm_rep=list(norm_rep1,norm_rep2)
    EMD_metric_comp_raw_all_samples[ind,]=EMD_metric(raw_rep)
    EMD_metric_comp_norm_all_samples[ind,]=EMD_metric(norm_rep)
    ind=ind+1
  }
  saveRDS(EMD_metric_comp_raw_all_samples, paste(outdir,"EMD_metric_comp_raw_all_samples_all_cells.rds",sep=""))
  saveRDS(EMD_metric_comp_norm_all_samples, paste(outdir,"EMD_metric_comp_norm_all_samples_all_cells.rds",sep=""))
  EMD_all=rbind(EMD_metric_comp_raw_all_samples,EMD_metric_comp_norm_all_samples)
  ref=c(rep("raw",nsample/2),rep("norm",nsample/2))
  df=data.frame(EMD_all,ref,sample=rownames(EMD_all))
  ggdf <- melt(df, id.var = c("sample","ref"),
               value.name = "expression", variable.name = "antigen")
  #ggplot(ggdf,aes(x=expression,y=sample,color=ref))+geom_point(aes(colour = ref))+facet_wrap(~ref)
  ggplot(ggdf,aes(y=expression,x=sample,color=ref))+geom_boxplot(aes(colour = ref)) + theme(axis.text.x = element_text(angle = 45, hjust = 1))
  ggsave(paste(outdir,"EMD_metric_comp_raw_and_norm_all_samples_all_cells.png",sep=""))

  # ############################ 3. Clusters proportions accross rep
  # Compute different distances
  nclust=dim(props_table_norm)[1]
  nsample=dim(props_table_norm)[2]

  compute_dist <- function (props_table){
    nsample=dim(props_table)[2]
    nclust=dim(props_table)[1]
    Dist_props_table=matrix(nrow=5,ncol=nsample/2)
    colnames(Dist_props_table)=substring(colnames(props_table)[seq(1,nsample,2)],2)
    row.names(Dist_props_table)=c("Hell","TV","KL","BC","CW1")
    ind=1
    for (s in seq(1,nsample,2)){
      Dist_props_table[1,ind]=1/sqrt(2)*sqrt(sum((sqrt(props_table[,s])-sqrt(props_table[,s+1]))^2))
      Dist_props_table[2,ind]=1/2*sum(abs(props_table[,s]-props_table[,s+1]))
      Dist_props_table[3,ind]=sum(props_table[,s]*log(props_table[,s]/props_table[,s+1]))
      Dist_props_table[4,ind]=sum(sqrt(props_table[,s]*props_table[,s+1]))
      Dist_props_table[5,ind] = 1 - 4*sum(props_table[,s+1]/(props_table[,s]+props_table[,s+1])*
                                            (1-props_table[,s+1]/(props_table[,1]+props_table[,s+1])))/nclust
      ind=ind+1
    }
    return(Dist_props_table)
  }
  Dist_props_table_raw=compute_dist(props_table_raw)
  Dist_props_table_norm=compute_dist(props_table_norm)
  saveRDS(Dist_props_table_raw,paste(outdir,"Dist_props_table_raw_all_samples.rds",sep=""))
  saveRDS(Dist_props_table_norm,paste(outdir,"Dist_props_table_norm_all_samples.rds",sep=""))
}
